name: Learn Github Actions

on:
  workflow_dispatch:

jobs:
  learn_github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo Hello World

      - name: Check isi 
        run: ls -lah

      - name: Baca file1
        run: cat file1

      - name: Bikin file hantu 
        run: echo "Temporary" > temp.txt
